Reponame: code.arista.io/open-source-forks/go-sqlmock
Description: Sql mock driver for golang to test database interactions
Users:
  Maintainers:
    - rajshree.sanjayam@arista.com
  Supervisor: rajshree.sanjayam@arista.com
Epoch: 1
ObsoleteNames:
  - gerrit.corp.arista.io/open-source-forks/go-sqlmock
  - github.com/aristanetworks/go-sqlmock
